name: CI
on: [ push, pull_request ]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '14', '16' ]
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0
      - name: Setup Node 💿
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install development dependencies 📚
        run: npm ci --prefer-offline --no-audit --ignore-scripts
      - name: Check code style 🧽
        run: npm run prettier:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '14', '16' ]
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0
      - name: Setup Node 💿
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install development dependencies 📚
        run: npm ci --prefer-offline --no-audit --ignore-scripts
      - name: Check code style 🧽
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '14', '16' ]
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0
      - name: Setup Node 💿
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install development dependencies 📚
        run: npm ci --prefer-offline --no-audit --ignore-scripts
      - name: Check code style 🧽
        run: npm run test
