name: Release
on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please action
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      # The logic below handles the npm publication:
      - name: Checkout 📥
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v3
      - name: Setup Node 💿
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Install development dependencies 📚
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci
      - name: Build library 📦
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build

      - name: Publish to npm registry 🗜
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
